export const state = {
  preloaderRunning: false,
  preloaderRaf: null,
  zoomFallbackTimer: null,
  metersRaf: null,
  previewTimer: null,
  sourceTimer: null,
  previewIdx: 0,
  previewLayer: 'a',
  sourceIdx: 0,
  sourceLayer: 'a',
  loadStart: 0,
  loadDuration: 0,
  loadPct: 0,
  preloaderMode: 'desktop',
  mobileGrade: { exposure: 0, contrast: 0, highlights: 0, shadows: 0, saturation: 0 },
  mobileSliderChannels: null,
  heroTimer: null,
  heroIndex: 0,
  activeLayer: 'a',
  deckIndex: 0,
  deckCount: 0,
  deckTransitioning: false,
  deckAutoplay: false,
  deckPaused: false,
  deckAutoplayTimer: null,
  galleryTimer: null,
  galleryIdx: 0,
  deckViewportW: 0,
  deckViewportH: 0,
  touchStartX: 0,
  touchStartY: 0,
  deckInputReady: false,
  meterSizeKey: '',
};

export const els = {};
