/**
 * Portfolio projects — primary edit file.
 * Add images[], youtubeStart, or ?t= on YouTube URLs as needed.
 */
export const PROJECTS = [
  {
    id: 'testing1',
    category: 'Car Videography',
    title: 'A night out in Constanta',
    description:
      'This short montage shows the true wonders of the Constanta city in Romania. It shows the wonders of car enthusiasts.',
    type: 'youtube',
    media: 'https://youtu.be/KfnDJxuzy_M?t=10',
    images: [],
  },
  {
    id: 'artistic',
    category: 'Artistic',
    title: 'Chromatic Silence',
    description: 'Fine-art photography exploring light, texture, and negative space.',
    type: 'image',
    media: 'PORTOFOLIO%20IMAGES%20ESAD/Artistic/Shadow%20Man.jpg',
    images: [
      'PORTOFOLIO%20IMAGES%20ESAD/Artistic/Bird.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Artistic/Duck%20Curious.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Artistic/Duck%20Pose.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Artistic/Duck%20Side.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Artistic/Shadow%20Man.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Artistic/Stairs%20Tree%20Bottom%20Up.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Artistic/Stairs%20Tree%20Light.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Artistic/Water%20Drop.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Artistic/WindowsFaces.jpg',
    ],
  },
  {
    id: 'interrogation-room',
    category: 'Short Film',
    title: 'Interrogation Room',
    description: 'A tense, 1-minute short film set in an interrogation room.',
    type: 'youtube',
    media: 'https://youtu.be/QF7jhiKabMA?t=15',
    images: [],
  },
  {
    id: 'landscapes',
    category: 'Landscapes',
    title: 'Natural & Urban Horizons',
    description: 'A mix of natural scenery and urban landscapes captured through a unique lens.',
    type: 'image',
    media: 'PORTOFOLIO%20IMAGES%20ESAD/Landscapes/Sunset%20Tree.jpg',
    images: [
      'PORTOFOLIO%20IMAGES%20ESAD/Landscapes/Blurry%20Forest.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Landscapes/Curb.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Landscapes/Glass%20Sky%20Reflection.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Landscapes/Hallway%20Golden.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Landscapes/Hallway%20Red.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Landscapes/Sunset%20Tree.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Landscapes/Sunset%20With%20River.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Landscapes/The%20Beach.jpg',
    ],
  },
  {
    id: 'simulacra',
    category: 'Short Film',
    title: 'Simulacra',
    description: 'A short film exploring the philosophical concepts of reality, imitation, and perception.',
    type: 'youtube',
    media: 'https://youtu.be/oWZhconmblA?t=190',
    images: [],
  },
  {
    id: 'buildings',
    category: 'Buildings',
    title: 'Structural Light',
    description: 'Architecture and interiors framed with geometric precision.',
    type: 'image',
    media: 'PORTOFOLIO%20IMAGES%20ESAD/Buildings/3%20Buildings.jpg',
    images: [
      'PORTOFOLIO%20IMAGES%20ESAD/Buildings/3%20Buildings.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Buildings/Castle%20Behind%20Leafs.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Buildings/Center%20Interest.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Buildings/Leaf%20Wall.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Buildings/Stairs%20Top%20Bottom.jpg',
      'PORTOFOLIO%20IMAGES%20ESAD/Buildings/Tall%20Building%20Black%20and%20White.jpg',
    ],
  },
];
